### ISSUE TITLE
[Feature request] Marshal ruby objects returned by server tasks

### ISSUE THREAD

**Issue by pencilcheck** [voltrb/volt#186]
It would be really nice if I can return a ruby object in server and pops back on the client side.

**Comment by ryanstout** [comment]
Marshal isn't supported by Opal.  Its not impossible, probably just quite a bit of work.  Might want to hit up the opal gitter and see what they think about it.  Really though, it would probably be easier to make a new serializer format, because marshal wasn't designed to take data from the client.  Marshaling something from the client would be a big security risk because you could load up any class and it would be easy from there to run arbitrary code (like the yaml exploits)  So really you need a format where you can whitelist allowed classes.  I'm going to close this for now, but I think its something we can revisit in a few months.

**Comment by ryanstout** [comment]
Something like this would be great: https://github.com/tarcieri/securemarshal

**Comment by pencilcheck** [comment]
I'm talking mostly one way flow from the server to the client not the other way around. The server tasks marshal into client is very useful that no other frameworks I know existing can do.
