### ISSUE TITLE
Feature Request: React Support

### ISSUE THREAD

**Issue by thiagoc7** [voltrb/volt#285]
I've just started working with Meteor + React, and I can tell that it's a fantastic match. You get a flux implementation for free.

Is it possible to achieve [this](http://react-in-meteor.readthedocs.org/en/latest/) same kind of integration with Volt?

I fell that it could really boost Volt's adoption, and would open the framework for a huge frontend community, with lots of plugins.

Cheers!

**Comment by ryanstout** [comment]
@thiagoc7 react and volt do some things differently under the hood, without getting into the technical details, it doesn't really make since for us to try to integrate react.  That said, if there's some things you like it react, we can probably try to build something similar in volt.

**Comment by akshatpradhan** [comment]
@ryanstout I'm no ruby guy, but instead of putting HTML in the views, can we use ruby to generate the html? For example in react, we can do something like 

`ReactDOM.render(<div id="msg">Hello World!</div>, mountNode);`

Can we make it so that ruby generates the html?

**Comment by ryanstout** [comment]
@akshatpradhan There's good reasons (besides just historical) to separate controllers and presentation.  The strongest of which for me is volts future plans to allow you to build mobile apps using rubymotion.  Splitting presentation from controllers means that we'll be able to share our core controller logic between web and ios and android (and possibly others)  Facebook is already having problems with code duplication when building react native apps (because of the coupling between presentation and controller)  Most people using react native are building a separate app using the same tools.  My goal with volt is to build multiple "apps" from a single codebase, sharing most everything except for presentation.  This is not to say the way react does it can't be made to work, but the separation I think makes it easier to share code while keeping presentation customized to each platform.

That said, it would be possible for us to make the switch to rendering from within ruby, but its not something I have time for at the moment.  (unless someone wants to sponsor it as a feature, hehe)

**Comment by thiagoc7** [comment]
Hi @ryanstout, I think that `react` can be just an alternative template language for `volt`.
There's no need to change any core concept of the framework, or promote any coupled integration.

This is what `meteor` is doing, they give us an easy way to render `react components`, and create a react mixim that connects the component to a reactive data source.

I opened this issue because this [addon](https://github.com/meteor/react-packages/blob/5c9fb0581f7240293c1c3606206e44e1b91337e3/packages/react-meteor-data/meteor-data-mixin.jsx) implementation does not seem to be very complex, and maybe you think that this react support could boost volt's adoption.

Thanks for your work in volt. With or without react, it's just amazing.
Cheers

**Comment by ryanstout** [comment]
@thiagoc7 Thanks.  So at one level we could implement something like meteor is doing, but volt tries to be a bit higher level abstraction for your data layer.  So we do things like two way bindings, which make it so you don't need to manually handle field change events.  If you don't mind manually hooking things up, then you can basically do what meteor is doing by rendering a react component in a controllers {action}_ready method, and then using Computations to update the react component.  Personally though, I like the volt way better (obviously).
