### ISSUE TITLE
Closable tags: <:tag_name> instead of <:tag_name />

### ISSUE THREAD

**Issue by Canifex** [voltrb/volt#335]
Quoting the docs:
> Like normal html tags, they should be closed. (``<:tag_name />``)

Actually, if we think of HTML5 instead of XHTML, they should not be closed. "Normal" HTML5 tags (not XHTML!) - e. g.``<br>`` - do not have a closing `/`. So, to be up to date, we should change this to ``<:tag_name>`` and recommend this instead.

See also: http://stackoverflow.com/questions/1946426/html-5-is-it-br-br-or-br

**Comment by ryanstout** [comment]
There's a few different categories of html tags, only void tags should not have the /   Imho, volts custom tags don't follow into that category. The / tells the parser that there won't be any content between <:tag_name>and some future <:/tag_name>  The reason that works on void tags is because there is a white list of tags. In volt we don't know at template compile time if the tag will receive content, so we need the /

**Comment by ryanstout** [comment]
http://www.programmerinterview.com/index.php/html5/void-elements-html5/
